/// Flutter icons UploadIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  UploadIcon
///      fonts:
///       - asset: fonts/UploadIcon.ttf
///
/// 
/// * MFG Labs, Copyright (C) 2012 by Daniel Bruce
///         Author:    MFG Labs
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.mfglabs.com/
///
import 'package:flutter/widgets.dart';

class UploadIcon {
  UploadIcon._();

  static const _kFontFam = 'UploadIcon';
  static const _kFontPkg = null;

  static const IconData upload = IconData(0xf02f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
